#!/usr/bin/env bash
# Run Nginx as nginx
chmod 777 /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-available/default
pkill -f apache2
sudo -u nginx service nginx start

