#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#    Listens on port 80.
#    Returns a page containing "Holberton School" when queried
#    at the root with a curl GET request.
apt-get update
apt-get install -y nginx
mkdir /usr/share/nginx/html
touch /usr/share/nginx/html/index.html
echo "Holberton School" > /usr/share/nginx/html/index.html
printf %s "
    server {
        listen      80 default_server;
        listen      [::]:80 default_server;
        location / {
            root      /usr/share/nginx/html/;
            index     index.html;
        }
        location /redirect_me {                                                       
            return 301 https://www.youtube.com/watch?v=8s22PZRXAIY;                                                 
        }
    }
" > /etc/nginx/sites-available/default

service nginx restart
